services:
  # Laravel App (PHP-FPM)
  laravel:
    build:
      context: ./Laravel12_app
    container_name: laravel12_app
    volumes:
      - ./Laravel12_app:/var/www
      - /var/www/vendor
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: demoDocker
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      SESSION_DRIVER: file
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - app_net

  # Nginx Server
  server:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./Laravel12_app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app_net

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demoDocker
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

  # React (Vite)
  react:
    build:
      context: ./React_app
    container_name: react_app
    volumes:
      - ./React_app:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    networks:
      - app_net

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge
